#!/bin/bash

#install basic program
yum update -y
yum install -y vim 
yum install -y man 
yum install -y zlib-devel bzip2-devel openssl-devel xz-libs wget
yum install bind-utils -y
yum install -y man 
yum install -y git 
yum groupinstall ‘Development Tools‘  -y
yum install sqlite-devel libxslt-devel libxml2-devel java-1.7.0-openjdk libpcap-devel nano openssl-devel zlib-devel libffi-devel gdbm-devel readline-devel nano wget -y
yum install -y lrzsz
yum install -y gcc

yum install -y fping 
yum install -y whois

#install tcpdump
yum install -y tcpdump

##install hydra
yum install -y hydra

#install nc 
yum install -y nc 

#install metasploit 

cd /opt

wget http://downloads.metasploit.com/data/releases/metasploit-latest-linux-x64-installer.run 
chmod +x metasploit-latest-linux-x64-installer.run

/opt/metasploit-latest-linux-x64-installer.run

#install python 2.7
cd /opt
wget https://www.python.org/ftp/python/2.7.13/Python-2.7.14.tar.xz
xz -d Python-2.7.14.tar.xz
tar -xvf Python-2.7.14.tar
cd Python-2.7.14
./configure --prefix=/usr/local
make
make install
ln -s -f /usr/local/bin/python2.7  /usr/bin/python
sed -i 1d /usr/bin/yum
sed -i '1i#!/usr/bin/python2.7' /usr/bin/yum


#instll pip 
cd /tmp
wget https://pypi.python.org/packages/source/s/setuptools/setuptools-17.5.tar.gz#md5=533c868f01169a3085177dffe5e768bb
tar -zxvf setuptools-17.5.tar.gz
cd setuptools-17.5
python setup.py install
easy_install pip
pip install ipython
pip install shadowsocks
#
#
##stop iptables
#
#

#
#install nmap v7 ncat nping 

rpm -ivh https://nmap.org/dist/nmap-7.60-1.x86_64.rpm
rpm -ivh https://nmap.org/dist/ncat-7.60-1.x86_64.rpm
rpm -ivh https://nmap.org/dist/nping-0.7.60-1.x86_64.rpm

#install ssr
wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/ssr.sh && chmod +x ssr.sh && bash ssr.sh

#install sqlmap
cd /opt 
git clone https://github.com/sqlmapproject/sqlmap.git
ln -s /opt/sqlmap/sqlmap.py /usr/bin/sqlmap
#
